Feature v2
TIBCOSoftware/vscode-extension-mashling pull request #14
Opened 2018-05-24 09:16 UTC by tbhatia1912

Issue #12 and #13 fix

2018-05-24 15:51 UTC, owen-pengtao requested changes

2018-05-24 15:51 UTC, owen-pengtao commented on src/extension.ts
> +			console.log(gopath);
please remove the console.log

2018-05-24 16:00 UTC, owen-pengtao approved these changes

2018-05-25 03:54 UTC, tbhatia1912 commented
Latest code for v2 is in this branch and has not been merged to master yet. I have resolved the conflict in readme and tested and verified this code.

@owen-pengtao Could you please merge this branch to master?

2018-05-25 04:03 UTC, merged